### ISSUE TITLE
Playing 360 video - explore

### ISSUE THREAD

**Issue by grzegorzkrukowski** [vimeo/PlayerKit#17]
When playing 360 video player doesn't support "looking around" with device or rotating using drag gestures.

Is it planned to support this like most players do ? Or only way is to handle that on our own ?

**Comment by ghking** [comment]
Playing 360 video is not supported by the included `RegularPlayer`. We have an internal class called `CardboardPlayer` that conforms to the `Player` protocol and relies on GVRSDK, the Google Cardboard framework (https://github.com/googlevr/gvr-ios-sdk). 

The reason we don't include `CardboardPlayer` in `PlayerKit` is that GVRSDK is a static library. This causes two problems:

1) It's ~250 MB. Github's individual file size limit is 100 MB, so if you want to follow Cocoapod's recommendation and check in your `Pods` directory (https://guides.cocoapods.org/using/using-cocoapods.html#should-i-check-the-pods-directory-into-source-control) you're out of luck. We don't want to force everyone to ignore this recommendation just to include our pod.

2) Cocoapods doesn't support static libraries as transitive dependencies anyway (https://github.com/CocoaPods/CocoaPods/issues/2926). There is an issue filed on GVRSDK to provide it as a dynamically linked framework (https://github.com/googlevr/gvr-ios-sdk/issues/174), but who knows if that will go anywhere.

Sorry about that! Open to alternative ideas as always.
