### ISSUE TITLE
Plans to migrate to swift 4?

### ISSUE THREAD

**Issue by spencerkohan** [vimeo/PlayerKit#18]
It looks like this project is somewhat recently active, but I don't see a swift 4 branch or any reference to the new language version.  Will this project support swift4 at any point?

**Comment by ghking** [comment]
@spencerkohan I'll be upgrading it in the next week or so. It's currently in Swift 3.2 though, so you shouldn't be having any problems using it with a Swift 4 project. Are you running into issues?

**Comment by richkzad** [comment]
There's an issue in RegularPlayer's FillModeCapable extension with AVPlayerLayer.videoGravity, which is now a AVLayerVideoGravity type, not a String.

**Comment by grzegorzkrukowski** [comment]
You can use this together with Swift 4, but you need to make sure PlayerKit is makred as Swift3

Easiest way to do this is to add this to your PodFile:

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if
            target.name == 'PlayerKit'

            target.build_configurations.each do |config|
                config.build_settings['SWIFT_VERSION'] = '3.2'
            end
        end
    end
end
```

But I think it will be worth upgrading to swift 4 on main branch soon.

**Comment by ghking** [comment]
Version 1.2.0 is now Swift 4 🎉🎉🎉
