### ISSUE TITLE
CredStore - performQuery - Error copying matching creds

### ISSUE THREAD

**Issue by jacobokoenig** [vimeo/PlayerKit#26]
Hi, I added the player to a view as in the example project, but I am getting this error:

CredStore - performQuery - Error copying matching creds.  Error=-25300, query={
    class = inet;
    "m_Limit" = "m_LimitAll";
    "r_Attributes" = 1;
    sync = syna;
}

I have no idea how to debug this. Any ideas?

My implementation in Swift 4 to set the video is a little bit different

        player.set(AVURLAsset(url: URL(string: videoURLString)!))
        player.play()

**Comment by ghking** [comment]
@jacobo360 What's the URL you're using?

**Comment by jacobokoenig** [comment]
Here is one for example: https://player.vimeo.com/video/187767563. I also tried a different format: https://vimeo.com/253136458/7be89ef27f

**Comment by ghking** [comment]
Gotcha. Check out my response on this issue: https://github.com/vimeo/PlayerKit/issues/29
