### ISSUE TITLE
Loop a video

### ISSUE THREAD

**Issue by 08irfan** [vimeo/PlayerKit#28]
@ghking  Iam a pro account holder of Vimeo.
Integrated PlayerKit as per instructions.
I am unable to loop a video.
Moreover, I am unable to determine when a video ends.

**Comment by ghking** [comment]
Hey @08irfan, looping is not a built-in functionality of PlayerKit.

If you want to loop your video, you can implement the `func playerDidUpdateTime(player: Player)` function in your `PlayerDelegate`. If you compare that time against `player.duration`, once they are the same (or the same within a margin to accounting for precision), you can set the player time back to 0.
