### ISSUE TITLE
Extended example for playing w/ Vimeo Video URL?

### ISSUE THREAD

**Issue by jyaunches** [vimeo/PlayerKit#29]
Hello!

I'm successfully using the Vimeo API to retrieve information about my Business account videos.

I'm trying to incorporate PlayerKit into our iOS application and am using your example code to just do the very baseline.

I'm receiving an error back of '-999'.

<img width="1278" alt="screen shot 2018-02-22 at 3 24 33 pm" src="https://user-images.githubusercontent.com/372490/36569956-c88795a2-17e4-11e8-8ce4-c111ee200f09.png">

Not sure if I'm using the right URL. I'm pulling it out of the returned JSON from a GET request for that video.

<img width="974" alt="screen shot 2018-02-22 at 3 27 55 pm" src="https://user-images.githubusercontent.com/372490/36570015-016a49aa-17e5-11e8-92dc-b3de492078d4.png">

Am I using the wrong URL? Are there newer examples I can reference?

**Comment by jyaunches** [comment]
Interestingly... I just saw the same error when running the example project. But, it still loads the video.

<img width="1398" alt="screen shot 2018-02-22 at 4 33 33 pm" src="https://user-images.githubusercontent.com/372490/36572019-5fcfb22e-17ee-11e8-8771-4c0fc3bdf8c4.png">

When I bring my vimeo URL into the example project.. I actually get a different error. And the video doesn't load!

<img width="1383" alt="screen shot 2018-02-22 at 4 34 25 pm" src="https://user-images.githubusercontent.com/372490/36572022-63094d10-17ee-11e8-9aab-08887691397b.png">

**Comment by ghking** [comment]
Hi @jyaunches, The URL you are using is the URL of the video web page. What you're looking for is the URL of a video file. This can be retrieved by requesting the video object from the API (https://developer.vimeo.com/api/playground/me/videos/) and using the `link` URL in one of the objects in the `files` array. The `files` array will only be present if you have a Pro, Business, or Live account.
