### ISSUE TITLE
How to ID a RegularPlayer Instance

### ISSUE THREAD

**Issue by 08irfan** [vimeo/PlayerKit#31]
Unable to find tag property in RegularPlayer class. How can I ID an instance.
@ghking

**Comment by ghking** [comment]
@08irfan ID the instance in what way?

**Comment by 08irfan** [comment]
@ghking I have an array of regular players. Want to ID/tag them.

**Comment by ghking** [comment]
Are you referring to the `UIView` property called `tag`? `RegularPlayer`s are just `NSObject`s. How you want to hold references to or identify them is up to you.

**Comment by 08irfan** [comment]
@ghking from an array of regular players how to determine which instance triggered the delegate method/s?

**Comment by ghking** [comment]
The `Player` instance that called the delegate method is passed in as the `player` argument. This is common behavior for most delegate APIs (including Apple's).

**Comment by 08irfan** [comment]
@ghking Yeah I understand. Suppose I have 100 or more player instances in an array.. It will be inconvenient to check one by one.
Instead, there should be O(1) approach to pinpoint index of player instance.
May be iam unable to convey my point here :)

**Comment by ghking** [comment]
Why do you need to find it in the array if a reference to it is already provided by the argument? You're looking for the index specifically? If so, the performance of an `index(of: player)` on arrays even much, much larger than 100 elements will be unnoticeable to a user.

**Comment by 08irfan** [comment]
@ghking let me tell you the complete scenario.
I have a tableview in which videos can be played/paused in each cell.
I have an array of players corresponding to cells of tableview.
On video end i have to show a custom message in cell. That's why i want index of the player which finished playing so that i can update specific cell in the tableview.

**Comment by ghking** [comment]
Consider storing an array of not `RegularPlayers`, but models containing the video URL and message. This way, the `RegularPlayer`s are recycled along with the cells and you only have a small number of them in memory at any given time. You can use the models in the array to populate each cell and its player.

**Comment by 08irfan** [comment]
@ghking User can play and pause the video at any time in each cell . So reusing the player can cause issue. Thats why seperate player for each cell to mantain state.

**Comment by ghking** [comment]
State (current time, playing or not, etc.) can also be stored as properties of the model. You really don't want a bunch of players hanging out in memory.

**Comment by 08irfan** [comment]
@ghking thanks for your input. Kindly check issue #30 too.
