### ISSUE TITLE
Type 'AVLayerVideoGravity' (aka 'NSString') has no member 'resizeAspect'

### ISSUE THREAD

**Issue by AnikeshiOS** [vimeo/PlayerKit#32]
Type 'AVLayerVideoGravity' (aka 'NSString') has no member resizeAspect. This issue raise just after installed pods

**Comment by Jumhyn** [comment]
Hi @AnikeshiOS! Sorry for the delay in response. What version of Swift are you using? Newer versions of Swift should import `AVLayerVideoGravity` as its own `struct` type, not `NSString'.

**Comment by Jumhyn** [comment]
Hi @AnikeshiOS -- are you still experiencing this issue? If so, it would be great if you could provide us with the info requested above. Otherwise, we will close this issue in the next few days.

**Comment by nicolelehrer** [comment]
@AnikeshiOS closing this out, but feel free to reach out again if you encounter any issues.
