### ISSUE TITLE
Slow start of stream videos

### ISSUE THREAD

**Issue by Legonaftik** [vimeo/PlayerKit#42]
If user doesn't have fast internet connection then the player starts too late (sometimes it starts only when the whole video is downloaded). Could you, please, allow PlayerKit users to choose if they want to configure the player so it starts playing video ASAP. It should be very easy to implement since you're using AVPlayer under the hood. Providing us ability to set its `automaticallyWaitsToMinimizeStalling` property will be enough.

**Comment by rpassis** [comment]
Hi @Legonaftik,

Thanks for raising this issue and apologies for the delay in getting back to you.

If you still think this is a feature that might be useful to you and the wider community, we encourage you to open a PR and I'll work with you to have it incorporated into the codebase.

Thanks!
Rog

**Comment by Legonaftik** [comment]
Hi @rpassis 

I opened the PR: https://github.com/vimeo/PlayerKit/pull/67
