### ISSUE TITLE
Is VideoFiles still a supported Scope?

### ISSUE THREAD

**Issue by ugowe** [vimeo/PlayerKit#44]
I have a Pro account and I'm trying to play videos from the `files` array as mentioned here: https://github.com/vimeo/PlayerKit/issues/29

However, `VideoFiles` seems to no longer be a case for the `Scope` enum.

Is there another way to access that `link` URL in the `files` array?
@jasonhawkins @Jumhyn 

![screen shot 2018-08-23 at 2 46 47 pm](https://user-images.githubusercontent.com/16910028/44547716-f868ab00-a6e9-11e8-9d56-b7c7cab1e67d.png)

**Comment by ugowe** [comment]
@nicolelehrer

**Comment by rpassis** [comment]
Hey @ugowe

Firstly apologies for taking so long to respond!

We recently updated our networking library (https://github.com/vimeo/VimeoNetworking) to include the `VideoFiles` scope. So if this is something you are still working on, could you please give it a try and let us know how you go? I'll close this issue in the meantime.

Thanks!
Rog
