### ISSUE TITLE
How do I tell that the video is finished playing?

### ISSUE THREAD

**Issue by hawflakes** [vimeo/PlayerKit#45]
PlayerKit's been pretty easy to use but I have a few issues that have been a bit of a struggle.
I've been trying to determine when a video has finished playing with the following:

```
    if player.time >= player.duration {
            delegate?.didFinishPlaying(controller: self)
        }
```
But there are times when a streaming video never quite reaches the end. i.e. `time` is a couple seconds off from `duration` but I can't get the thing to play to the end.

Is the solution to extend `RegularPlayer` to callback when `AVPlayerItemDidPlayToEndTime` gets posted?

**Comment by supperspidey** [comment]
Hello @hawflakes . There are a few ways to detect if the you're at the end of a video, but I think using the `AVPlayerItemDidPlayToEndTime` notification might be the most correct one. In my experiment, that notification callback was called at the correct time for multiple videos.

`PlayerKit` is unfortunately not subscribing to the notification yet. In case you fork `PlayerKit`, did the `AVFoundation`'s notification solve your problem?

**Comment by supperspidey** [comment]
@hawflakes I will close this issue for now, but if you have any question, please let us know.
