### ISSUE TITLE
Authentication support for Vimeo .mp4 files

### ISSUE THREAD

**Issue by anish190** [vimeo/PlayerKit#59]
Hello,
   I am using Vimeo Pro account to access the private videos. Our server team provides us the actual .mp4 CDN url from the Vimeo as part of their api response and I am able to play the video in the mobile app. But considering security aspect, the user/hacker can get the actual url by snooping the api using proxy like Charles and get access to actual videos. Can we use any authentication mechanism from the mobile app to prevent access to .mp4 url without prior authentication?

**Comment by bedranfleck** [comment]
Is this repo still alive? I don't see much activity in the issues, nor in the code. This question is interesting for my project also.

**Comment by rpassis** [comment]
Hi there

Yes this repo is still alive and continues to be used internally by the Vimeo app. 

The question you are asking is out of scope for this library though. There are many different things you can do to try and protect transactional data on your private APIs but without intimate knowledge of your setup and what your acceptable risk might be there is no way we could responsibly comment on this. 

I’d personally suggest you look more generally into securing APIs via certificate pinning, data obfuscation etc. 

Good luck with it!
Rog
