### ISSUE TITLE
Add carthage support

### ISSUE THREAD

**Issue by igorbiscanin** [vimeo/PlayerKit#60]
Add the option to install the PlayerKit via carthage dependency manager.

**Comment by rpassis** [comment]
Hi @igorbiscanin and thanks for opening this issue!

We have added this to our backlog and it should eventually make its way into the codebase. In the meantime, you are very welcome to open a PR and I'll work with you to have it merged and available to the developer community.

Cheers,
Rog

**Comment by rpassis** [comment]
Fixed by #85

**Comment by divyeshmakwana96** [comment]
@rpassis I am getting this error: Dependency "PlayerKit" has no shared framework schemes for any of the platforms: iOS

**Comment by rpassis** [comment]
Hi there, and thanks for getting in touch!

We haven't tagged a new version with Carthage support yet but you should be able to build it directly from the `develop` branch. 

In your Cartfile:

```
github "Vimeo/PlayerKit" "develop"
```

Then run:

```sh
$ carthage bootstrap --platform ios
```

And you should see output:

```sh
*** No Cartfile.resolved found, updating dependencies
*** Cloning PlayerKit
*** Checking out PlayerKit at "df438ea6d71093aac6adeca501338def623d80c4"
*** xcodebuild output can be found in /var/folders/73/lnfrs9hx1nn6khr3r3lzh5600000gp/T/carthage-xcodebuild.5149I4.log
*** Building scheme "PlayerKit-iOS" in PlayerKit.xcworkspace
```
