### ISSUE TITLE
Architecture Question (Follow-Up to #69)

### ISSUE THREAD

**Issue by ghost** [vimeo/PlayerKit#70]
I have a follow-up question about #69 and would love to get an **opinion** on this to make sure I am using `PlayerKit` correctly.

With `PlayerKit`, there is a protocol `ProvidesView` which allows the player to return a view. In my app, I have two objects: `Video` and `Song`. Therefore, I have two different players: `VideoPlayer` and `AudioPlayer`. The `VideoPlayer` returns a view backed by `AVPlayerLayer` just like your sample project. However, `AudioPlayer` returns a `UIView` with an image.

In my `PlayerViewController`, I have next/previous buttons so that a user can skip items. This means the view from `ProvidesView` needs to update after every tap to next/previous button.

My question is, since the view from `ProvidesView` is completely different between a `VideoPlayer` and `AudioPlayer`, would you have just 1 `PlayerViewController` to handle this? I included the code below of how this would be done (thanks to your help in #69 ).  If not 1 `PlayerViewController`, maybe I should create 2 different view controllers: `VideoPlayerViewController` and `AudioPlayerViewController`? For songs (audio), I would use `SDWebImage` to load images for the view where as with videos, I would follow what is in your sample project with RegularPlayer --- it seems this should not all be done with 1 view controller? 

Thank you!

```swift
protocol Player { // Omitted for brevity }
protocol ProvidesView { // Omitted for brevity }

class VideoPlayer: Player, ProvidesView { // Omitted for brevity }
class AudioPlayer: Player, ProvidesView { // Omitted for brevity }

class MyViewController<T: Player & ProvidesView>: UIViewController {

    var player: T!
    
    static func configured(with player: T) -> MyViewController {
        let vc = MyViewController()
        vc.player = player
        return vc
    }

    private func didTapNextButton() {
        // Need to update view with a video or image depending on if the object is a `Video` or `Song` object
    }

    private func didTapPreviousButton() {
        // Need to update view with a video or image depending on if the object is a `Video` or `Song` object
    }
}
```

**Comment by rpassis** [comment]
Hi there @johnswifttt,

A possible approach is for your custom views to handle the button taps and updated themselves, then pass on the message to the view controller via a delegate method:

```swift
class CustomPlayerView: UIView {
    // ...
    @IBAction func nextTapped() { 
        // Update view here then `self.delegate?.didTapNext()`
    }
}
```

**Comment by ghost** [comment]
Hi @rpassis,

That's interesting, so with that approach the playback controls (next/previous buttons) and the background view (playerLayer or image) are combined into one custom view. I updated the code below to try and match what you stated. If I understand this correctly, this is what it would look like:

Please notice the `extension MyViewController: VideoPlayerViewDelegate`  and `extension MyViewController: AudioPlayerViewDelegate`. I guess it makes sense to have 2 delegate methods here since the views are different? Also, is this what you had in mind?

```swift
protocol Player { // Omitted for brevity }
protocol ProvidesView { // Omitted for brevity }

class VideoPlayer: Player, ProvidesView { // Omitted for brevity }
class AudioPlayer: Player, ProvidesView { // Omitted for brevity }

protocol VideoPlayerViewDelegate: class {
    func didTapNext()
}

class VideoPlayerView {
    weak var delegate: VideoPlayerViewDelegate?
    
    @IBAction func nextTapped() {
        // Update view here then:
        self.delegate?.didTapNext()
    }
}

protocol AudioPlayerViewDelegate: class {
    func didTapNext()
}

class AudioPlayerView {
    weak var delegate: AudioPlayerViewDelegate?
    
    @IBAction func nextTapped() {
        // Update view here then:
        self.delegate?.didTapNext()
    }
}

class MyViewController<T: Player & ProvidesView>: UIViewController {
    
    var player: T!
    
    static func configured(with player: T) -> MyViewController {
        let vc = MyViewController()
        vc.player = player
        return vc
    }
}

extension MyViewController: VideoPlayerViewDelegate {
    func didTapNext() {
        
    }
}

extension MyViewController: AudioPlayerViewDelegate {
    func didTapNext() {
        
    }
}
```

**Comment by rpassis** [comment]
That looks like it could work. I'd use a single protocol `PlayerViewDelegate` for all types since they share the same interface but that's just a personal preference.

Good luck with it!

**Comment by ghost** [comment]
`PlayerViewDelegate` is better as you said. 

Thanks again for taking a look and opinion on this!  🙂
