### ISSUE TITLE
Question about AVPlayerItemDidPlayToEndTime

### ISSUE THREAD

**Issue by ghost** [vimeo/PlayerKit#72]
I noticed that `AVPlayerItemDidPlayToEndTime` is not part of `PlayerKit`. Do you plan on supporting this? 

If not, how would you suggest to implement it -- should it be part of `PlayerDelegate`? If yes, then we would need to fork the repo right to include it? Or maybe it should not be part of the delegate?

Note, I seen issue #45

**Comment by rpassis** [comment]
Hi John there are no short term plans to add `AVPlayerItem` notifications to `PlayerKit` however if you feel this is a feature that could be useful for yourself and others, you are more than welcome to create a PR and we will work with you to get it merged.

I'd suggest looking into the `RegularPlayer` class, in particular where we create the new `AVPlayerItem` and setup KVO observation for some of its properties. That's probably the ideal place to also setup notifications and relay them on via a callback to the `PlayerDelegate`.

**Comment by ghost** [comment]
Makes sense, thanks! I'll check to see if it is useful, if so, I'll try to create a PR 👍 

Thank you for answering question!
