### ISSUE TITLE
does your lib support rtsp/rtmp?

### ISSUE THREAD

**Issue by fukemy** [vimeo/PlayerKit#77]

**Comment by rpassis** [comment]
Hi there and thanks for opening this issue

`PlayerKit` is not a player itself, it is simply an abstraction layer that can work with various player types. So while we don't specifically support RTSP/RTMP (or any other playing technology for that matter), if the player that exists underneath `PlayerKit` is capable of RTSP/RTMP playback, then you will most likely be able to use `PlayerKit` to control content playback.

Please let me know if you have any other questions!
Rog
