### ISSUE TITLE
Vimeo Video Not Playing.

### ISSUE THREAD

**Issue by kopsPrmr** [vimeo/PlayerKit#78]
Download The Code And  Replace The URL(https://github.com/vimeo/PlayerKit/blob/master/Example/PlayerKit/video.mp4?raw=true) With (https://vimeo.com/282875052) Video Is Not Load And Playing. Can You Plz Help Me For This.

**Comment by rpassis** [comment]
Hi there,

The URL you are passing to the player is not a video but a webpage.

If you'd like to play a Vimeo video using PlayerKit, you will first need to get the video file URL via our API and then pass that url to the player.

For details on how to interact with our API see https://developer.vimeo.com/. You can also check out our [iOS networking library](https://github.com/vimeo/VimeoNetworking/)

Please feel free to open another issue if you have trouble navigating those resources.

Rog
