### ISSUE TITLE
How to play private vimeo video link? 

### ISSUE THREAD

**Issue by cemalsayin** [vimeo/PlayerKit#96]
Hi I have private video link like that **"https://vimeo.com/'videoID'/'privatecode'"** how to play it my ios app?

**Comment by rpassis** [comment]
Hi there,

The URL you mentioned above is not a video but a webpage.

If you'd like to play a Vimeo video using PlayerKit, you will first need to get the video file URL via our API and then pass that `url` to the player.

For details on how to interact with our API see https://developer.vimeo.com/. You can also check out our [iOS networking library](https://github.com/vimeo/VimeoNetworking/)

Please feel free to open another issue if you have trouble navigating those resources.

Rog
