### ISSUE TITLE
UIWebview is deprecated

### ISSUE THREAD

**Issue by Cleversou1983** [vimeo/PlayerKit#98]
Hi! I'm using the SDK for playing videos and worked fine, however, when I'm send the app for the AppStore, I get an warning complaining about the UIWebview (I think it's on the AFNewtorking lib)... Any plans to update the lib or us Alamofire for example? Thanks a lot!

**Comment by bedranfleck** [comment]
Seeing as this is still being maintained by some of the devs, I would like to weigh in on this conversation: Is there a release plan featuring the replacement of UIWebView API on this SDK in the near future?

**Comment by bedranfleck** [comment]
@rpassis Thanks for answering the previous question at #96. Maybe you could give us a hand here too?

**Comment by rpassis** [comment]
Hi there this library does not use `UIWebView` for anything, and it doesn't have any third party dependencies that may rely on it. If you are by any chance referring to `VimeoNetworking` we have released new versions address this specific issues https://github.com/vimeo/VimeoNetworking/releases. This version was also published to Cocoapods.

**Comment by rpassis** [comment]
https://github.com/vimeo/VimeoNetworking/releases
