### ISSUE TITLE
Sutitles

### ISSUE THREAD

**Issue by Cleversou1983** [vimeo/PlayerKit#99]
Hi there! Does the VideoPlayer support subtitles? How It works? Thanks a lot!

**Comment by Cleversou1983** [comment]
Anyone?

**Comment by rpassis** [comment]
Hi there, 

The player we offer here is a wrapper around `AVPlayer` so it should support subtitles out of the box. If you're after some pointers on where to get started, take a look at the `TextTrackMetadata` protocol and the `selectedTextTrack` property of the `RegularPlayer`.

Rog

**Comment by Cleversou1983** [comment]
@rpassis Thanks a lot, Roger... I'll check it out.
Cleverson
